source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'jbuilder', '~> 2.8', '>= 2.8.0'
gem 'puma', '~> 3.7'
gem 'rails', '~> 7.1.0'
gem 'sass-rails', '~> 6.0', '>= 6.0.0'
gem 'sqlite3'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'
gem 'webpacker', '>= 3.3.1'

gem 'omniauth', '~> 2.1', '>= 2.1.0'
gem 'omniauth-barong', '~> 0.1.3'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'capybara', '~> 3.0', '>= 3.0.0'
  gem 'pry-rails', '~> 0.3.6'
  gem 'selenium-webdriver', '>= 3.11.0'
end

group :development do
  gem 'listen', '~> 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.1.0'
  gem 'web-console', '>= 3.6.0'
end
